spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/realms/SpringBoot/protocol/openid-connect/certs
          issuer-uri: http://localhost:8081/auth/realms/SpringBoot
  application:
    name: Libreria
  datasource:
    password: 'hcXPKC94.'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    url: jdbc:mysql://localhost:3306/libreria?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
#  ssl:
#  key-store-password: password_certificate
#  key-store-type: PKCS12
#  key-store: /home/debian/ssl-cert/certificate.p12
  compression:
    enabled: 'true'
  port: '8081'

  security:
  require-ssl: 'true'

keycloak:
  resource: libreria

logging:
  level:
    it:
      frankladder: DEBUG
    org:
      springframework: INFO
